### ISSUE TITLE
Allow game window to be resized

### ISSUE THREAD

**Issue by TheCraftKid** [ClemensCodeCentral/type-type-revolution#13]
Currently, the method that handles window resizing does not function at all. I propose completely scrapping the existing implementation and find a more proper way to allow for said functionality.

**Comment by roblesda768** [comment]
I agree because if anyone has looked at the code. All the graphics are hard coded to the specs of the Clemens monitors on full screen mode.

**Comment by NasonNL** [comment]
ISS DONE BOI

**Comment by NasonNL** [comment]
Resolved

**Comment by NasonNL** [comment]
It can resize now.
